name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        subcommand: ['fmt', 'build', 'clippy', 'test']
        include:
            - subcommand: 'clippy'
              # treat warnings as errors
              args: '--all-features -- -D warnings'
            - subcommand: 'fmt'
              args: '--check'
            - subcommand: 'build'
              args: '--all-features'
            - subcommand: 'test'
              args: '--all-features'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo ${{ matrix.subcommand }} ${{ matrix.args }}
